# Generated by Django 4.0.5 on 2023-05-23 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('uri', models.TextField()),
                ('database_name', models.TextField()),
                ('username', models.TextField(blank=True)),
                ('password', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FileObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default=None, max_length=255)),
                ('file', models.FileField(upload_to='files')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.project')),
            ],
        ),
        migrations.CreateModel(
            name='ColumnObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default=None, max_length=100)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.fileobject')),
            ],
        ),
    ]
